;; Add this to the .emacs to get it to load this as the init script

(when (require 'flycheck nil 'noerror)
  (add-hook 'after-init-hook #'global-flycheck-mode))


(load "funcs.el")
(if (eq system-type 'darwin)
        (load "mac-config.el")
      )
(if (eq system-type 'gnu/linux)
        (load "linux-config.el")
      )
(load "environment.el")
(load "libraries.el")
(load "lithium-config.el")
(load "shortcuts.el")

;;(load "python-config.el")
(load "javascript-config.el")

(provide "_emacs")

